version: '3.9'
services:
  flask_web:
    build: .
    container_name: flask_web_container
    environment:
      # для отладки (при запуске в релиз убрать!)
      - FLASK_DEBUG=0
      ## Позволяет отслеживать процесс работы приложения в командной строке
      - PYTHONUNBUFFERED=True
    ports:
      - "4565:4565"
