openapi: 3.0.0
info:
  title: "Parking REST API"
  description: "Получение кол-во свободных мест"
  version: "1.0.0"
servers:
  - url: "/api"
paths:
  /parking:
    post:
      operationId: "parking.get"
      tags:
        - parking
      summary: "Get parking"
      requestBody:
        description: "get parking"
        required: True
        content:
          application/json:
            schema:
              x-body-name: "parking"
              $ref: "#/components/schemas/Parking"
      responses:
        "201":
          description: "Successfully get Parking"
components:
  schemas:
    Parking:
      type: "object"
      required:
        - parking
      properties:
        parking:
          type: "string"